### ISSUE TITLE
Character editor hierarchy dropdown is blank

### ISSUE THREAD

**Issue by SneakyEvil0** [MattFiler/LegendPlugin#530]
Hello,I tried to create a new human npc and when i tried to create limb of this npc the dialog slide is fully blank.

<img width="1357" height="602" alt="Image" src="https://github.com/user-attachments/assets/72833577-a7b6-4c77-8d9b-6d23cf90101f" />

**Comment by MattFiler** [comment]
Thanks for the report, this should be fixed in .042 on staging

**Comment by SneakyEvil0** [comment]
Hi, I’d like to reopen this case since the bug is still happening, now in the “Add New” dialog box for Human [NPCs.

<img width="932" height="699" alt="Image" src="https://github.com/user-attachments/assets/cf9239a5-7d49-4be0-b7bb-6988b1e60a31" />

**Comment by MattFiler** [comment]
Thanks, this should now be fixed in 0.43 -> it's out now via GitHub/ModDB/Nexus, and will be out later for Steam 👍
